services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/portainer/data/portainer/data:/data
    ports:
      - 9443:9443
      # - 8001:8000  # Remove if you do not intend to use Edge Agents